name: Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
#  schedule:
#    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: oprypin/find-latest-tag@v1
        with:
          repository: letsencrypt/boulder
        id: boulder

      - run: echo "Boulder is at version ${{ steps.boulder.outputs.tag }}"

      - uses: actions/checkout@v2
        with:
          repository: letsencrypt/boulder
          ref: ${{ steps.boulder.outputs.tag }}
          path: boulder

      - name: Apply our patches
        run: ./patch.sh

      - name: Build the binaries
        run: ./build.sh

      - name: Get next version
        uses: reecetech/version-increment@2021.11.2
        id: version
        with:
          scheme: calver
          #increment: patch

      - run: echo "Would tag this images as ${{ steps.version.outputs.version }}"

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PIPELINE_PAT_TEST }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/hakwerk/test:latest
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
