name: Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
#  schedule:
#    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: oprypin/find-latest-tag@v1
        with:
          repository: letsencrypt/boulder
        id: boulder

      - run: echo "Boulder is at version ${{ steps.boulder.outputs.tag }}"

      - uses: actions/checkout@v2
        with:
          repository: letsencrypt/boulder
          ref: ${{ steps.boulder.outputs.tag }}
          path: boulder

      - name: Run another script
        run: |
          cd boulder
          ls -latr

# TODO: apply patches

# TODO: build docker, push ?? iff different from latest image, possible determined from tags?
# see https://github.com/marketplace/actions/version-increment
